In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [3]:
df = pd.read_csv("/content/Vehicle_Maintenance_Cost_Dataset_1000 (1).csv")
df.head()

,Vehicle_ID,Brand,Vehicle_Age,Mileage,Engine_Size_CC,Fuel_Type,Transmission,Service_Count,Previous_Repair_Cost,Usage_Type,Driving_Condition,Maintenance_Cost
0,1,BMW,4,11556,2000,Petrol,Automatic,7,1828,Commercial,City,4157.34
1,2,Toyota,3,62314,1800,Diesel,Manual,16,4931,Personal,Highway,7773.21
2,3,Kia,9,217187,1000,Hybrid,Manual,5,5719,Personal,City,8891.31
3,4,Ford,4,29312,3000,Hybrid,Automatic,3,2940,Commercial,Mixed,4506.68
4,5,Ford,13,25656,2000,Diesel,Automatic,20,5066,Personal,Mixed,8910.84

In [4]:
lr = linear_model.LinearRegression()
lr.fit(df[['Vehicle_Age', 'Mileage', 'Service_Count', 'Previous_Repair_Cost']],df.)

LinearRegression()

   Vehicle_Age  Mileage  Service_Count  Previous_Repair_Cost
0            5    50000             10                  2500

In [10]:
predicted_cost = lr.predict([[5,50000,10,2500]])
print(round(predicted_cost[0]),"Rs")

5750 Rs

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(